# Generated by Django 4.2.1 on 2023-06-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_shippingdetail_review_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
