# Generated by Django 4.2.1 on 2023-06-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_quality_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
